### PR TITLE
Only schedule update if prop value has changed

### PR DESCRIPTION
**Pull request by micahjon**
Add a check to `reflectiveProp` that gives it similar behavior to `useState` and `attributeChangedCallback`: an update is only scheduled if the prop's value has changed.

Fixes [#192](https://github.com/matthewp/haunted/issues/192)

### CODE REVIEW

**Comment by matthewp** [comment]
Looks good, would you mind rebasing with master to see if the tests pass? Sorry again for missing this.

**Comment by micahjon** [comment]
Hey @matthewp, no worries, looking forward to getting this wrapped up.

I'm fairly new to rebasing and could use some guidance on this one. As far as I can tell, my branch is up-to-date and only one commit (this PR) ahead of your master. 
image

Also, I believe the Travis CI build will continue to fail as long as there's the unresolved Typescript warning (fixed in https://github.com/matthewp/haunted/pull/223). If you merge that PR or fix it yourself, I think you'll find that the checks start passing.

**Comment by matthewp** [comment]
Ah, you're right!

**Comment by matthewp** [comment]
Ok, now a rebase. From your branch: `git rebase master && git push -f origin only-update-if-prop-value-changed `

**Comment by micahjon** [comment]
Cool, thanks @matthewp, I think we're good to go

**Pull request merged**
