### PR TITLE
WIP feature/context

### LINKED ISSUE #17: Add useContext(Context): ContextValue
I think this might need context implementation first of all.

I have been thinking about this for quite a while:), but was struggling with design of the API,
I think hooks can simplify the API and finally we can have context in DOM. 

As a solution `CustomEvents` can be used, since the `CustomEvents` are synchronous and you can pass `detail` object to it, parent provider could listen to an event and provide the context value in the same object or consumer can pass subscriber function that provider will call when context value changes.

API can be:

context
```
export const Context = createContext(defaultValue)
```
app
```
import { Context } from 'context';
// ... .provide can be a directive that gets the value and 
// assigns to prop of any DOM element, it can also 
// just wrap whole element, but this way you can easily debug it from elements inspector
html`
   <div .value=${Context.provide(contextValue)}>
       ....someCode
       ....and somewhere in a tree
               <my-element></my-element>
   </div>
`
```
my-element
```
import { Context } from 'context';

function MyElement() {
    const contextValue = useContext(Context);

    return html`
      <div>${contextValue}</div>
    `;
}

customElements.define('my-element', component(MyElement));
```

Relationship can be defined by reference of created context (like shown above) or alternatively by unique string, but then drawback is name collision.

With references drawback is, if` `my-element` is living in different source code, it needs to mock Context and intercept import to inject mocked module, otherwise it is perfect.

Let me know what you think

### PR DESCRIPTION
**Pull request by askbeka**
Fixes #17

### CODE REVIEW

**Comment by matthewp** [comment]
This looks amazing!

**Comment by matthewp** [comment]
@askbeka Let me know when you feel "good" about the implementation and I'll give it a more thorough review and look for holes. Also if you could do a test or two that would be amazing.

**Comment by askbeka** [comment]
@matthewp Thanks, sure. I'll try make it as soon as possible

**Comment by askbeka** [comment]
@matthewp So, I have tried to reuse as much as possible and make it look clean:), but it has drawbacks:

Since useEffects is async request for context goes after first render so useContext will call setState in useEffect, which will cause unnecessary update.
useEffect was used in useContext since Provider component assigns event listeners on useEffect, so request has to be dispatched after.

So event listeners assignment and dispatch for context subscription and getting current value have to be in same phase

**Comment by askbeka** [comment]
apparently any node can dispatchEvents, since all Nodes implement EventTarget and any node can listen for Events, so creation of custom-element seems unnecessary.
I can dispatch the event from comment or text and handle it in document fragment

**Comment by matthewp** [comment]
Hey @askbeka, not trying to rush you or anything. Just letting you know that your branch needs to be rebased. Would you mind elaborating on what the current challenges are? Looking at the code it looks fine to me.  Do you not think it's ready (the rebase aside)?

**Comment by askbeka** [comment]
I was waiting for virtual components to be available. Will do rebase and
adopt virtual components today

**Comment by askbeka** [comment]
Will have to postpone till weekend:)

**Comment by matthewp** [comment]
Great! I'll take a look tomorrow and likely merge/release then.

**Comment by matthewp** [comment]
Looks great!

**Pull request merged**
