### PR TITLE
Mention hyperHTML too

### PR DESCRIPTION
**Pull request by WebReflection**
This project works for hyperHTML (6 months out before lit-html) so it'd be cool to not make it a lit-html thing only.

Thanks.

### CODE REVIEW

**Comment by WebReflection** [comment]
any particular reason this is being ignored ?

**Comment by matthewp** [comment]
I haven't decided if I want to support other libraries yet. It happens to work with hyperHTML at present but might not in the future if we start to depend on more lit-html internals such as the directives as is being discussed [here](https://github.com/matthewp/haunted/issues/27).

**Comment by WebReflection** [comment]
just FYI, the reason I've created [neverland](https://github.com/WebReflection/neverland#neverland-experimental) is exactly the same reason @askbeka opened that ticket: needing Shadow DOM to provide hooks is overkill for 90% of _hyperHTML_ use cases, I'd say 100% since even _HyperHTMLElement_ doesn't really need Shadow DOM to work well.

I've explained that in both [this part of the Medium post](https://medium.com/@WebReflection/neverland-the-hyperhtmls-hook-a0c3e11324bb#b9a9), and also in my initial tweet when I've discovered [haunted worked already with hyperHTML](https://twitter.com/WebReflection/status/1057552119555911680).

I am also not asking you to care much about _hyperHTML_, 'cause being _lit-html_ is an after project that replicated pretty much everything, I'd be eventually my responsibility to be sure whatever haunted does works in _hyperHTML_ too, and it'd be also my responsibility to file another PR to remove _hyperHTML_ from the README if I realize this project eventually diverged and hooked itself into _lit-html_ internals.

Hopefully I've clarified some of your thoughts on this.

**Comment by matthewp** [comment]
Ok I'll merge it. I very much doubt support for hyperHTML will ever be broken even if we adopt some of the directive stuff, the core `component()` should continue to work for any library that returns a fragment or templateresult.

Would very much appreciate it if you returned the favor and mentioned Haunted somewhere in hyperHTML's docs. 😀

**Comment by WebReflection** [comment]
it's now in the readme too: https://github.com/WebReflection/hyperHTML#hyperhtml

thanks 👋

**Pull request merged**
