### PR TITLE
Allow to pass observedAttributes as an option and make BaseElement argument optional in component()

### LINKED ISSUE #110: A way to declare `observedAttributes` inline
How about providing `observedAttributes` like this:

    component(() => html`...`, HTMLElement, { observedAttributes: [...] }));

I'd also either make the second argument optional, or put it into the options object:

    component(() => html`...`, { baseElement: HTMLElement, observedAttributes: [...], ... }));

I could make a PR if this API is fine.

### PR DESCRIPTION
**Pull request by sgtpep**
Closes #110.

### CODE REVIEW

**Comment by matthewp** [comment]
I think there's something going on with the build, it's unrelated to your change, so I'll take a look

**Comment by matthewp** [comment]
CI is passing again in master, if you want to rebase. Sorry for the inconvenience!

**Comment by matthewp** [comment]
Thanks @sgtpep, I'll probably release this tomorrow.

**Comment by sgtpep** [comment]
@matthewp Thank you! I hope I haven't messed up with type definitions as I'm new to TypeScript and not very confident with it. Maybe it's worth looking at it by some typing affocionado, as well.

**Pull request merged**
