### PR TITLE
add initializer argument to useReducer

### PR DESCRIPTION
**Pull request by nlundquist**
added this third argument to useReducer so it can be used in the same manner as the example here: https://reactjs.org/docs/hooks-reference.html#usereducer

### CODE REVIEW

**Comment by nlundquist** [comment]
I've realized the type here is too restrictive. The `initialState` is not necessarily of type S if you're using an `initializer` to perform a transformation on some arbitrary data to type S.

**Comment by nlundquist** [comment]
I believe I have corrected that with the changes in my last commit.

**Comment by matthewp** [comment]
This looks great, thanks!

**Comment by matthewp** [comment]
Out in 4.7.0.

**Pull request merged**
