### PR TITLE
docs: add a TypeScript example page

### PR DESCRIPTION
**Pull request by joryphillips**
I ran into some minor typing challenges when defining custom elements in TypeScript, and after solving the issue, thought some documentation might help others. Happy to modify or reorganize this however it best helps.

### CODE REVIEW

**Review by bennypowers — CHANGES_REQUESTED** [review]
Can you add an example of using `declare global { inteface Window { HTMLElementTagNameMap { 'my-profile': HTMLElement & FigureProps } } }`?

**Comment by joryphillips** [comment]
@bennypowers How does this look? Added an example for `this` too, based on #177 
Sorry for the messy PR -- using Git and writing docs is hard, apparently 😄

**Comment by joryphillips** [comment]
> 🤔 I'd think that the type of `component()` could probably be improved to accept function with a generic `this` binding that extends HTMLElement

I think absolutely true. I'd like to work on that next, then update the docs to remove, if successful?

**Review by bennypowers — APPROVED** [review]
LGTM

**Pull request merged**
