### PR TITLE
chore: Component generic that allows `this` to be HTMLElement 

### PR DESCRIPTION
**Pull request by joryphillips**
This PR allows `this` to be designated as an HTMLElement (or type extended from it) in functions passed to `component()`

i.e.
```js
function App(this: HTMLElement, { prop }) {
```

This is branched from my TypeScript conversion test PR, which helped me a lot in doing this. I can rebase if needed.

I made just about everything an `HTMLElement` instead of `Element`, and I think that is probably going to be correct in most cases, but I might be missing something.

The crux of the PR is that `GenericRenderer` currently designates `this` as `unknown`. My approach was to create a conditional type to figure out if we're dealing with a regular or virtual component in this location. I am sure there are other ways! Happy to make changes, discuss, etc. 😄

### CODE REVIEW

**Comment by micahjon** [comment]
Hey @matthewp , any chance we could get this merged? 

Since it's just types, it should be low-risk to merge, and would be nice to get out of the way before the lit-html v2 refactor. 

Thanks! Realize you've got a lot on your plate with Astro.

**Comment by joryphillips** [comment]
Let me know if there is anything I can / need to do to help get this merged!

**Comment by bennypowers** [comment]
here's the patch for anyone that needs this before release hits npm

<details><summary><code>patches/haunted+4.8.2.patch</code></summary>

```diff
diff --git a/node_modules/haunted/lib/component.d.ts b/node_modules/haunted/lib/component.d.ts
index ab325c0..5d840f4 100644
--- a/node_modules/haunted/lib/component.d.ts
+++ b/node_modules/haunted/lib/component.d.ts
@@ -1,9 +1,9 @@
 import { GenericRenderer, RenderFunction } from './core';
-interface Renderer<P extends object> extends GenericRenderer {
+interface Renderer<P extends object> extends GenericRenderer<HTMLElement, P> {
     (this: Component<P>, host: Component<P>): unknown | void;
     observedAttributes?: (keyof P)[];
 }
-declare type Component<P extends object> = Element & P;
+declare type Component<P extends object> = HTMLElement & P;
 declare type Constructor<P extends object> = new (...args: unknown[]) => Component<P>;
 interface Creator {
     <P extends object>(renderer: Renderer<P>): Constructor<P>;
diff --git a/node_modules/haunted/lib/core.d.ts b/node_modules/haunted/lib/core.d.ts
index ba3ba1e..0e16a96 100644
--- a/node_modules/haunted/lib/core.d.ts
+++ b/node_modules/haunted/lib/core.d.ts
@@ -1,7 +1,10 @@
 import { ComponentCreator } from './component';
 import { ContextCreator } from './create-context';
-declare type GenericRenderer = (this: unknown, ...args: any[]) => unknown | void;
-declare type RenderFunction = (result: unknown, container: DocumentFragment | Element) => void;
+import { NodePart } from 'lit-html';
+declare type Component<P> = HTMLElement & P;
+declare type ComponentOrVirtualComponent<T extends HTMLElement | NodePart, P extends object> = T extends HTMLElement ? Component<P> : NodePart;
+declare type GenericRenderer<T extends HTMLElement | NodePart, P extends object = {}> = (this: ComponentOrVirtualComponent<T, P>, ...args: any[]) => unknown | void;
+declare type RenderFunction = (result: unknown, container: DocumentFragment | HTMLElement) => void;
 interface Options {
     render: RenderFunction;
 }
@@ -9,7 +12,7 @@ declare function haunted({ render }: Options): {
     component: ComponentCreator;
     createContext: ContextCreator;
 };
-export { haunted as default, Options, GenericRenderer, RenderFunction };
+export { haunted as default, Options, GenericRenderer, RenderFunction, ComponentOrVirtualComponent };
 export { useCallback } from './use-callback';
 export { useController } from './use-controller';
 export { useEffect } from './use-effect';
diff --git a/node_modules/haunted/lib/create-effect.d.ts b/node_modules/haunted/lib/create-effect.d.ts
index 73bb584..b9c44a9 100644
--- a/node_modules/haunted/lib/create-effect.d.ts
+++ b/node_modules/haunted/lib/create-effect.d.ts
@@ -1,4 +1,4 @@
 import { State, Callable } from './state';
-declare type Effect = (this: State) => void | VoidFunction;
+declare type Effect = (this: State) => void | VoidFunction | Promise<void>;
 declare function createEffect(setEffects: (state: State, cb: Callable) => void): (callback: Effect, values?: unknown[] | undefined) => void;
 export { createEffect };
diff --git a/node_modules/haunted/lib/scheduler.d.ts b/node_modules/haunted/lib/scheduler.d.ts
index a66ae89..77728be 100644
--- a/node_modules/haunted/lib/scheduler.d.ts
+++ b/node_modules/haunted/lib/scheduler.d.ts
@@ -1,7 +1,8 @@
 import { State } from './state';
 import { commitSymbol, phaseSymbol, updateSymbol, effectsSymbol, Phase, EffectsSymbols } from './symbols';
-import { GenericRenderer } from './core';
-declare abstract class BaseScheduler<R extends GenericRenderer, H> {
+import { GenericRenderer, ComponentOrVirtualComponent } from './core';
+import { NodePart } from 'lit-html';
+declare abstract class BaseScheduler<P extends object, T extends HTMLElement | NodePart, R extends GenericRenderer<T, P>, H extends ComponentOrVirtualComponent<T, P>> {
     renderer: R;
     host: H;
     state: State<H>;
diff --git a/node_modules/haunted/lib/use-callback.d.ts b/node_modules/haunted/lib/use-callback.d.ts
index 3e7c26f..ae557f9 100644
--- a/node_modules/haunted/lib/use-callback.d.ts
+++ b/node_modules/haunted/lib/use-callback.d.ts
@@ -1,2 +1,9 @@
+/**
+ * @function
+ * @template {Function} T
+ * @param    {T} fn - callback to memoize
+ * @param    {unknown[]} inputs - dependencies to callback memoization
+ * @return   {T}
+ */
 declare const useCallback: <T extends Function>(fn: T, inputs: unknown[]) => T;
 export { useCallback };
diff --git a/node_modules/haunted/lib/use-context.d.ts b/node_modules/haunted/lib/use-context.d.ts
index 240c8d9..c298e20 100644
--- a/node_modules/haunted/lib/use-context.d.ts
+++ b/node_modules/haunted/lib/use-context.d.ts
@@ -1,3 +1,9 @@
 import { Context } from './create-context';
+/**
+ * @function
+ * @template T
+ * @param    {Context<T>} context
+ * @return   {T}
+ */
 declare const useContext: <T>(Context: Context<T>) => T;
 export { useContext };
diff --git a/node_modules/haunted/lib/use-controller.d.ts b/node_modules/haunted/lib/use-controller.d.ts
index 75ccd6b..08a3fec 100644
--- a/node_modules/haunted/lib/use-controller.d.ts
+++ b/node_modules/haunted/lib/use-controller.d.ts
@@ -10,8 +10,9 @@ import { ReactiveController, ReactiveControllerHost } from '@lit/reactive-elemen
  *
  * Use this hook to convert a ReactiveController into a Haunted hook.
  *
- * @param createController A function that creates a controller instance. This
- * function is given a HauntedControllerHost to pass to the controller. The
+ * @param {<C extends ReactiveController>(host: ReactiveControllerHost) => C} createController A function that creates a controller instance.
+ * This function is given a HauntedControllerHost to pass to the controller. The
  * create function is only called once per component.
+ * @return {ReactiveController} the controller instance
  */
 export declare function useController<C extends ReactiveController>(createController: (host: ReactiveControllerHost) => C): C;
diff --git a/node_modules/haunted/lib/use-effect.d.ts b/node_modules/haunted/lib/use-effect.d.ts
index 647d930..27e8877 100644
--- a/node_modules/haunted/lib/use-effect.d.ts
+++ b/node_modules/haunted/lib/use-effect.d.ts
@@ -6,5 +6,5 @@ declare function setEffects(state: State, cb: Callable): void;
  * @param {unknown[]} [dependencies] - list of dependencies to the effect
  * @return {void}
  */
-declare const useEffect: (callback: (this: State<unknown>) => void | VoidFunction, values?: unknown[] | undefined) => void;
+declare const useEffect: (callback: (this: State<unknown>) => void | Promise<void> | VoidFunction, values?: unknown[] | undefined) => void;
 export { setEffects, useEffect };
diff --git a/node_modules/haunted/lib/use-layout-effect.d.ts b/node_modules/haunted/lib/use-layout-effect.d.ts
index 669c6e3..4c313f2 100644
--- a/node_modules/haunted/lib/use-layout-effect.d.ts
+++ b/node_modules/haunted/lib/use-layout-effect.d.ts
@@ -1,3 +1,9 @@
 import { State } from './state';
-declare const useLayoutEffect: (callback: (this: State<unknown>) => void | VoidFunction, values?: unknown[] | undefined) => void;
+/**
+ * @function
+ * @param  {Effect} callback effecting callback
+ * @param  {unknown[]} [values] dependencies to the effect
+ * @return {void}
+ */
+declare const useLayoutEffect: (callback: (this: State<unknown>) => void | Promise<void> | VoidFunction, values?: unknown[] | undefined) => void;
 export { useLayoutEffect };
diff --git a/node_modules/haunted/lib/use-memo.d.ts b/node_modules/haunted/lib/use-memo.d.ts
index f26269c..14e9dc0 100644
--- a/node_modules/haunted/lib/use-memo.d.ts
+++ b/node_modules/haunted/lib/use-memo.d.ts
@@ -1,2 +1,9 @@
+/**
+ * @function
+ * @template T
+ * @param  {() => T} fn function to memoize
+ * @param  {unknown[]} values dependencies to the memoized computation
+ * @return {T} The next computed value
+ */
 declare const useMemo: <T>(fn: () => T, values: unknown[]) => T;
 export { useMemo };
diff --git a/node_modules/haunted/lib/use-reducer.d.ts b/node_modules/haunted/lib/use-reducer.d.ts
index b5aba01..ef18ae9 100644
--- a/node_modules/haunted/lib/use-reducer.d.ts
+++ b/node_modules/haunted/lib/use-reducer.d.ts
@@ -1,3 +1,14 @@
 declare type Reducer<S, A> = (state: S, action: A) => S;
+/**
+ * Given a reducer function, initial state, and optional state initializer function, returns a tuple of state and dispatch function.
+ * @function
+ * @template S State
+ * @template I Initial State
+ * @template A Action
+ * @param {Reducer<S, A>} reducer - reducer function to compute the next state given the previous state and the action
+ * @param {I} initialState - the initial state of the reducer
+ * @param {(init: I) => S} [init=undefined] - Optional initializer function, called on initialState if provided
+ * @return {readonly [S, (action: A) => void]}
+ */
 declare const useReducer: <S, I, A>(_: Reducer<S, A>, initialState: I, init?: ((_: I) => S) | undefined) => readonly [S, (action: A) => void];
 export { useReducer };
diff --git a/node_modules/haunted/lib/use-ref.d.ts b/node_modules/haunted/lib/use-ref.d.ts
index 29936a1..2df8ec6 100644
--- a/node_modules/haunted/lib/use-ref.d.ts
+++ b/node_modules/haunted/lib/use-ref.d.ts
@@ -1,3 +1,9 @@
+/**
+ * @function
+ * @template T
+ * @param   {T} initialValue
+ * @return  {{ current: T }} Ref
+ */
 declare const useRef: <T>(initialValue: T) => {
     current: T;
 };
diff --git a/node_modules/haunted/lib/use-state.d.ts b/node_modules/haunted/lib/use-state.d.ts
index 7af597b..6ce904e 100644
--- a/node_modules/haunted/lib/use-state.d.ts
+++ b/node_modules/haunted/lib/use-state.d.ts
@@ -6,5 +6,5 @@ declare type StateUpdater<T> = (value: NewState<T>) => void;
  * @param {T} [initialState] - Optional initial state
  * @return {readonly [state: T, updaterFn: StateUpdater<T>]} stateTuple - Tuple of current state and state updater function
  */
-declare const useState: <T>(initialValue: T) => readonly [T extends (...args: any[]) => infer R ? R : T, StateUpdater<T extends (...args: any[]) => infer S ? S : T>];
+declare const useState: <T>(initialValue?: T | undefined) => readonly [T extends (...args: any[]) => infer R ? R : T, StateUpdater<T extends (...args: any[]) => infer S ? S : T>];
 export { useState };
diff --git a/node_modules/haunted/lib/virtual.d.ts b/node_modules/haunted/lib/virtual.d.ts
index a722169..6c0d6ac 100644
--- a/node_modules/haunted/lib/virtual.d.ts
+++ b/node_modules/haunted/lib/virtual.d.ts
@@ -1,6 +1,6 @@
 import { NodePart } from 'lit-html';
 import { GenericRenderer } from './core';
-interface Renderer extends GenericRenderer {
+interface Renderer extends GenericRenderer<NodePart> {
     (this: NodePart, ...args: unknown[]): unknown | void;
 }
 declare function makeVirtual(): (renderer: Renderer) => (...args: unknown[]) => (part: NodePart) => void;
```

</details>

**Comment by matthewp** [comment]
Out in 4.8.3

**Pull request merged**
