### PR TITLE
Convert dash attributes to camelCase props

### PR DESCRIPTION
**Pull request by jpray**
addresses https://github.com/matthewp/haunted/issues/55

### CODE REVIEW

**Comment by matthewp** [comment]
Perfect, thank you!

**Comment by lukeshiru** [comment]
This kinda messes with the type system, because the `Renderer` interface has `observedAttributes` set to be `keyof P` (`P` being the properties generic). So if I have something like this it doesn't work as expected:
```ts
const Counter: Renderer<{ initialCount: string }> = ({
	initialCount = "0", 
	...props
}) => {
	const [count, setCount] = useState(parseInt(initialCount, 10));
	console.log(props);

	return html`
		<div id="count">${count}</div>
		<button type="button" @click=${() => setCount(count + 1)}>
			Increment
		</button>
	`;
};

// The following doesn't work because we are observing the camelCase
// instead of initial-count, and if we change it to "initial-count" it breaks
// because is not a key of `P`
Counter.observedAttributes = ["initialCount"]; 
```

And it also fails if we do:

```ts
const Counter: Component<{ "initial-count": string }> = ({
	// initial-count never comes because it was converted to camelCase
	"initial-count": initialCount = "0",
	...props
}) => {
	const [count, setCount] = useState(parseInt(initialCount, 10));
	console.log(props);

	return html`
		<div id="count">${count}</div>
		<button type="button" @click=${() => setCount(count + 1)}>
			Increment
		</button>
	`;
};

// The following line now works and is observing the expected attribute
// but the error is now above.
Counter.observedAttributes = ["initial-count"];
```

**Comment by jpray** [comment]
@lukeshiru HTML tags and attributes are case-insensitive per the [spec](https://html.spec.whatwg.org/multipage/syntax.html#writing).  I think there is room to argue for a better approach to managing attribute/prop names, but the case-insensitive nature of HTML does need to be accounted for in some way.  For example:
```
{
  foo: 1,
  Foo: 2
}
```
is a valid JS object, but
```
<my-element foo="1" Foo="2"/>
```
is not a valid use of attributes in HTML.

Something like the following should work for you:
```
const Counter: Component<{ "initialCount": string }> = ({
	"initialCount": initialCount = "0",
	...props
}) => {
	const [count, setCount] = useState(parseInt(initialCount, 10));
	console.log(props);

	return html`
		<div id="count">${count}</div>
		<button type="button" @click=${() => setCount(count + 1)}>
			Increment
		</button>
	`;
};

// The following line now works and is observing the expected attribute
// but the error is now above.
Counter.observedAttributes = ["initial-count"];
```

**Comment by lukeshiru** [comment]
@jpray I know there is not an easy way to implement camelCase on web components, what I mean is that with your solution the issue is that `"initial-count"` is not a `keyof P`, so the compiler throws an error in the line `Counter.observedAttributes = ["initial-count"];`. because of that.

If you remove the transformation, then you can use kebab-case as in my second example, the compiler is happy about it and the transformation is done manually by aliasing on the function header.

You can check that lit-element doesn't do kebab to camel, and is because of things like this (they learned this the hard way with Polymer). Basically they avoid any kind of "unexpected parsing", so the dev always gets the expected props and values.

I'm not saying "remove this", a possible solution is to simply make `observedAttributes` in `Renderer` of type `string[]` instead of `keyof P`. We will loose auto-completion, but at least you can keep the transformation and TS doesn't throw errors.

**Comment by jpray** [comment]
@lukeshiru, I see now.  What you are saying makes total sense.  I agree observedAttributes would be better off being typed as string[].  Regardless of attribute to property conversion, the typings seem like they could use some love.  I'm not actively working on this project currently, but I'm sure your input would be well received if you want to open a new issue/PR.

**Pull request merged**
