### PR TITLE
Enhanced Typescript types definitions

### PR DESCRIPTION
**Pull request by alfredosalzillo**
Enhanced types definition.

#115 
#88

### CODE REVIEW

**Comment by Gladear** [comment]
Awesome work !
The only thing I noticed is that, in the StateUpdater the function takes a parameter that is the previous state.

Love it :relaxed:

**Comment by alfredosalzillo** [comment]
Thanks @Gladear 

> The only thing I noticed is that, in the StateUpdater the function takes a parameter that is the previous state.

Fixed

**Comment by Gladear** [comment]
While reading the fix, I saw another potential problem.

The initial value of the `useState` hook is optional. If no parameter is given, then the value of the state is `undefined`, which may not be included in type **T**.

There are two options that come to my mind to solve this, and both have flaws:
- Change the parameter of the callback as well as the return type of the hook to be `T | undefined`
This would mean that the user always has to check that the state isn't `undefined`, even if the state is never assigned to this value (not my favourite solution)
- Removing the optional parameter.
This would mean that the user has to hint the `undefined` type when using it, and would be forced to use `useState<TheType | undefined>(undefined)` if it is the initial value.

As I think that using `undefined` in the state is not common, I prefer the second option, but I'd like to know the though of someone else

**Comment by matthewp** [comment]
Thanks for this! The build is currently breaking in Haunted. I knew about this but forgot, 😔. I'll let you know when its fixed then this can be rebased.

**Comment by alfredosalzillo** [comment]
> While reading the fix, I saw another potential problem.
> 
> The initial value of the `useState` hook is optional. If no parameter is given, then the value of the state is `undefined`, which may not be included in type **T**.
> 
> There are two options that come to my mind to solve this, and both have flaws:
> 
> * Change the parameter of the callback as well as the return type of the hook to be `T | undefined`
>   This would mean that the user always has to check that the state isn't `undefined`, even if the state is never assigned to this value (not my favourite solution)
> * Removing the optional parameter.
>   This would mean that the user has to hint the `undefined` type when using it, and would be forced to use `useState<TheType | undefined>(undefined)` if it is the initial value.
> 
> As I think that using `undefined` in the state is not common, I prefer the second option, but I'd like to know the though of someone else

I don't know if is possible to have a type how can't accept undefined value.
For example:

```typescript
  type OnlyLoremIpsum = 'lorem ipsum';
  const onlyLoremIpsum: OnlyLoremIpsum = undefined;
```
This is valid in typescript even if the type only accept the value 'lorem ipsum'.

The only problem could be a NonNullabe type
```typescript

**Comment by alfredosalzillo** [comment]
> While reading the fix, I saw another potential problem.
> 
> The initial value of the `useState` hook is optional. If no parameter is given, then the value of the state is `undefined`, which may not be included in type **T**.
> 
> There are two options that come to my mind to solve this, and both have flaws:
> 
> * Change the parameter of the callback as well as the return type of the hook to be `T | undefined`
>   This would mean that the user always has to check that the state isn't `undefined`, even if the state is never assigned to this value (not my favourite solution)
> * Removing the optional parameter.
>   This would mean that the user has to hint the `undefined` type when using it, and would be forced to use `useState<TheType | undefined>(undefined)` if it is the initial value.
> 
> As I think that using `undefined` in the state is not common, I prefer the second option, but I'd like to know the though of someone else

I don't know if is possible to have a type how can't accept undefined value.
For example:

```typescript
  type OnlyLoremIpsum = 'lorem ipsum';
  const onlyLoremIpsum: OnlyLoremIpsum = undefined;
```
This is valid in typescript even if the type only accept the value 'lorem ipsum'.

The only problem could be the NonNullabe built in type:
```typescript
type NonNullable<T> = T extends null | undefined ? never : T;
```
but even using it as type of the useState give no error setting to undefined

```typescript
  useState<NonNullable<OnlyLoremIpsum>>(undefined);
  const test: NonNullable<OnlyLoremIpsum> = undefined;
```
If we remove the optional from the useState, we can alway pass undefined as value even if the type is NonNullable.

**Comment by Gladear** [comment]
This is because you are not using the _strictNullCheck_ flag of the compiler.
From [Typescript's documentation](https://www.typescriptlang.org/docs/handbook/compiler-options.html),
> In strict null checking mode, the `null` and `undefined` values are not in the domain of every type and are only assignable to themselves and `any` (the one exception being that `undefined` is also assignable to `void`).

**Comment by matthewp** [comment]
CI is passing again in master, if you want to rebase. Sorry for the inconvenience!

**Comment by matthewp** [comment]
Pinging @ceigey @jpray @Mateiadrielrafael @chase-moskal in case anyone wants to take a look at this PR before merging.

**Comment by matthewp** [comment]
Hey again, it looks like there's a merge conflict created when I merged another PR. If you could resolve this I'll merge this next and do a release. Thanks again.

**Comment by ceigey** [comment]
Hi, sorry for taking a while to look at this despite the ping - kept getting distracted.
One thing I was wondering was why:
```javascript
renderer: (this: T, el: P & T) => TemplateResult | void,
````
had `el: P & T` instead of just `el: P`; that's just because I haven't had a look at the library recently and I can't remember off the top of my head if `renderer` represents the "functional component" part or not.

If it is, then if I declare the following component renderer:
```javascript
type Props = { name: string }
let App = ({ name }) => {
   // ... useState, return html`......` etc
}
```
... how does TypeScript cope with that? As `{ name }` is just a subset of `P & T` (specifically it only represents the P part).

On the other hand, `{ name }` I imagine might be valid for `P | T` but then you might as well just write `P` by itself.

... buuuut....

If the actual value being fed into `App` is a HTMLElement or ShadowRoot of type `T` with extra properties described by `P`, then perhaps it's justified, especially if someone defines `App` like:
```javascript
let App = (element) => {
  let name = element.name
  // extra stuff here
}
```

But since we already have a `this` value idealy you'd be able to get the elements properties like this:
```javascript
function App(props) {
  let element = this
  let name = props.name
  // etc
}
```

----

So I think the hypothetical user acceptance test for this should be: _can I use this function as a valid renderer with TypeScript when TSC's strict mode is turned on?_

```javascript
interface Props {
  name: string
}

function App(props: Props) {
  console.log(this); // Expect a HTMLElement
  return html`<span>Hello, ${name}</span>`;
}
```

**Comment by matthewp** [comment]
Unrelated but I'm becoming more open to a Typescript conversion in order to smooth this sort of thing out. If it can be done without increasing file size. It will have to come after a couple of features currently in the works and I'd need someone other than me to do the heavy lifting as I lack the experience. So just putting the idea out there for a later time.

Shouldn't affect this PR, still want to get this in.

**Comment by Gladear** [comment]
Two things I said in #115 but did not see there at first:
The _package.json_ "typings" field refers to _index.d.ts_, a file that doesn't exist anymore. It should now reference _lib/haunted.d.ts_.
Also, the `withHooks` function does not exist anymore, so it should be removed from the typings file.

**Comment by alfredosalzillo** [comment]
Hi @ceigey, 

> If the actual value being fed into `App` is a HTMLElement or ShadowRoot of type `T` with extra properties described by `P`, then perhaps it's justified, especially if someone defines `App` like:
> 
> ```js
> let App = (element) => {
>   let name = element.name
>   // extra stuff here
> }
> ```

The input of the renderer function is the HTMLElement or ShadowRoot and not only the subset of observedProps, so the type is the same as the `this`.
To be correct the type of the `this`, should be `T & P` as well, or to be correct should be an instance of the `ComponentType<T,P>` returned by the `component` function.

**Comment by ceigey** [comment]
Ah, my perspective was completely wrong!

Ok, ignore my comments then. Looks good.

(for some reason, I kept thinking about the problems users would face if they had to pass data into to a function of that type, when really it's Haunted doing that in the background; and I forgot that the type contract only goes one way in TS e.g. consuming functions only ask for what they need and the function using other functions can't force it to accept a wider type, thus the push for optional nominal typing)

**Comment by matthewp** [comment]
Awesome, thanks so much @alfredosalzillo !  I opened https://github.com/matthewp/haunted/issues/124 to discuss possibly moving to TypeScript.

**Pull request merged**
