### PR TITLE
IE11

### PR DESCRIPTION
**Pull request by crisward**
Symbols aren't supported in IE11 - don't expect you to merge this, just thought I'd point it out.
What are the advantages to using symbols in this context?

### CODE REVIEW

**Comment by styfle** [comment]
From the looks of the code, they're effectively private fields. Without symbols, the properties are exposed publically.

https://github.com/matthewp/haunted/blob/a68de277a043a1dd6a09de0a4777c95ddf79ffda/src/core.js#L34

**Comment by matthewp** [comment]
That class itself is semi-privatish, here's where it's used: https://github.com/matthewp/haunted/blob/a68de277a043a1dd6a09de0a4777c95ddf79ffda/src/component.js#L12

The symbols are probably not needed any more, I'll have to think about it. But for the sake of getting this in can we create a little function in symbols.js that checks for compat?

```js
const symbolFor = typeof Symbol === 'function' ? Symbol.for : str => str;

export const phaseSymbol = symbolFor('haunted.phase');
...
```

**Comment by crisward** [comment]
Looks good to me.

**Comment by matthewp** [comment]
Awesome, thank you!

**Pull request merged**
