### PR TITLE
feat: add useController hook

### LINKED ISSUE #237: useController 🔥 ⚡️
With lit 2 out in RC, howzabout we implement `useController` in haunted?

I've got a working prototype at https://github.com/apollo-elements/apollo-elements/blob/a94dc32e68e89ea810ae067b7b20ac0427854ae8/packages/haunted/useController.ts based on lit-labs' react implementation

Worth a PR?

### PR DESCRIPTION
**Pull request by bennypowers**
* use useController to compose ReactiveControllers into haunted components
* tests useController
* documents useController in examples

Closes #237

### CODE REVIEW

**Comment by bennypowers** [comment]
build is failing on account of #236

**Comment by bennypowers** [comment]
I force-pushed this branch with a fix to the build error which also closes #236 

I resorted to an `as` type assertion. A little clumsy, but it works

**Review by matthewp — APPROVED** [review]
Looks great!

**Comment by michaeldgraham** [comment]
Thank you! <3

**Comment by johanventer** [comment]
This has broken builds for anyone who doesn't have `@lit/reactive-element` installed, as it was only added to `devDependencies`, so it not installed when you `npm i haunted`.

**Pull request merged**
