### PR TITLE
agnostic: haunted can use lit-html or lighterhtml

### PR DESCRIPTION
**Pull request by chase-moskal**
hello, please review this work making haunted agnostic about the rendering engine, allowing users to swap versions of `lit-html` or use `lighterhtml`

see the detailed commit message for more information

### CODE REVIEW

**Comment by chase-moskal** [comment]
@matthewp,

i wonder if we should expose some of the new functionality in `src/haunted.js`?

i held back, because i was worried that adding `lighterComponent` would bloat the bundle

currently, `src/lighter-component.js` references `lighterhtml.js` which re-exports from unpkg

but maybe the following additions could be exposed without risk? `configureComponent`, `configureVirtual`, `adaptLighterHtml`

let me know what you think

**Comment by chase-moskal** [comment]
pinging @WebReflection in case you're interested

**Comment by matthewp** [comment]
You're awesome. Initial look, I like it. Can give some better feedback likely tomorrow.

**Comment by matthewp** [comment]
@chase-moskal in #66 there was an API that I kind of like, what do you think about it?

```js
import { haunted } from 'haunted';

const { component } = haunted({ render });
```

Not much different from your current code, just renamed a bit. Another alternative is a Haunted constructor, but I'm not sure if this makes sense:

```js
import { Haunted } from 'haunted';

const haunted = new Haunted({ render });
const { component } = haunted;
```

I think the first makes a little more sense, just throwing out some ideas.

**Comment by chase-moskal** [comment]
@matthewp 

i do really like the ergonomics of a top-level `haunted` function which performs this kind of configuration, it's a nice developer experience — however i have two concerns:

```js
import { render, directive } from 'lit-html';
import { haunted } from 'haunted';
const { component, virtual } = haunted({ render, directive });
```

1. we also have to pass in the `directive` function from lit-html
    - i honestly haven't figured out what `directive` really is, or what's going on here
    - not sure what the lighterhtml equivalent to this might be?
    - if the user leaves `directive` undefined, would the `haunted` function return `virtual` as undefined?

2. it's not optimum without tree-shaking
    - we can ask devs to rely on tree-shaking in their build routines, but it would be nice if the recommended pattern worked nicely via unpkg without loading any unneeded code

if we can figure out the first concern, i think the `haunted` function would be nice sugar to add, even if the documentation ends up recommending the other pattern (to load stuff like `configureComponent.js` directly/individually)

**Comment by WebReflection** [comment]
not sure if it helps, but lighterhtml also exports a `useHook` utility too, which accept any `useRef` method that would couple a specific reference to a component.

```js
const {render, hook} = lighterhtml;
const {html, svg} = hook(useRef);

// example ...
const Button = component((text) => {
  const [i, increment] = useState(0);
  return html`
  <button onclick=${() => increment(i + 1)}>
    ${text} ${i}
  </button>`;
});
```

Beside that, I think all it would take to render via lighterhtml is:

```js
import { render, html } from 'lighterhtml';
import { haunted } from 'haunted';
const { component } = haunted({
  render: (what, where) => render(where, what)
});

customElements.define('my-comp', component(() => html`here I am`));
```

Theoretically, the same could be done for hyperHTML:

```js
import { bind } from 'hyperHTML';

const html = (...args) => bound => bound(...args);
const render = (what, where) => {
  return what()(bind(where));
};

import { haunted } from 'haunted';
const { component } = haunted({ render });

customElements.define('my-comp', component(() => html`here I am`));
```

If that's how it works, `hyperHTML` could export also a render and `html` or `svg` utility.

- - -

The problem I see here is that you're coupling this library with lit-html configuration.

For haunted purpose, the virtual thingy, directives, etc, makes no sense whatsoever.

Those are indeed all lit-html contracts I'm not sure why any other library should care about.

Maybe lit-html should provide a `lit` function to configure itself, so that `const { render, html } = lit({directive})` and nothing else needs to be bothered.

That would allow lit itself to be configured many times for different needs/directives, instead of having global side effects if directive changes all of a sudden ... right? (might be inaccurate since I don't lit-html at all).

**Comment by WebReflection** [comment]
P.S. I've read in the other thread quite some FUD around lit-html being the standard, using standards, etc, etc ...

Well, I hope their marketing selling point, since nothing is concretely being worked on, but any other library could use their same primitives once available cross browsers anyway, won't ruin this project focus, 'cause where I work we ship to millions hyperHTML based custom elements already (HyperHTMLElement) and haunted would be a very nice alternative to suggest for more convoluted scenarios that might like hooks simplification.

Please keep uo with the awesome work, and stop thinking about the future of standards once these will maybe look like something lit-html probably might do in some yer to come 😉

**Comment by matthewp** [comment]
@chase-moskal I wouldn't worry to much about the lit-html usage since lit-html still will be coming with Haunted and people can just use the normal API for it.

What I'm thinking is another entry point which doesn't have any of the lit-html stuff (so meaning no render and no virtual). I like the API suggested by @WebReflection here actually, because it means not needing to include lighterhtml as a dependency:

```js
import { render, html } from 'lighterhtml';
import { haunted } from 'haunted/core';
const { component } = haunted({
  render: (what, where) => render(where, what)
});

customElements.define('my-comp', component(() => html`here I am`));
```

> Note about that it is __haunted/core__, which is an entry that doesn't include virtual or lit-html render()

And then someone could even publish a `haunted-lighter` if they want that does the integration part.

**Comment by chase-moskal** [comment]
> lit-html still will be coming with Haunted and people can just use the normal API for it

yes, this is why i was very keen to leave haunted's api surface untouched to avoid any breaking changes

> What I'm thinking is another entry point which doesn't have any of the lit-html stuff

Yes, the current state of this PR reflects this objective

currently for lit-html

```js
import {configureComponent} from "haunted/src/configure-component.js"
import {render} from "lit-html"

const component = configureComponent({render})
```

currently for lighterhtml

```js
import {configureComponent} from "haunted/src/configure-component.js"
import {adaptLighterHtml} from "haunted/src/adapt-lighter-html.js"
import {render} from "lighterhtml"

const component = configureComponent({
  render: adaptLighterHtml(render)
})
```

note that this is exactly equivalent to what you guys are suggesting, however with the name "configureComponent" instead of "haunted"

the above pattern as currently implemented by this pr
- cleanly decouples haunted from lit-html or lighterhtml, requiring the consumer to import and pass in a render function themselves
- avoids any breaking changes: the render function is expected with lit-html's signature because that's what haunted supported first
- adaptLighterHtml is provided as a utility to adapt the lighterhtml render function to match lit-html's; this mostly exists to signal that lighterhtml is a first-class citizen for haunted

now, about "configureComponent" vs "haunted"
- i chose "configureComponent" in order to disambiguate it from "configureVirtual" (thus decoupling it from lit-html's "directive")
- if we combine "configureComponent" and "configureVirtual" into "haunted", then we are necessarily coupling with lit-html's signature (directive), thus my concern 1 of my previous post
- otherwise if we simply rename "configureComponent" to "haunted" (leaving "configureVirtual" separated), it puts "virtual" in the back seat (not usable via the "haunted" config function, this might be desirable?)

also, i think adding hyperhtml, via an "adaptHyperHtml" utility function to indicate support, would be awesome

just let me know if i'm misunderstanding any of the points you guys are making :)

**Comment by chase-moskal** [comment]
@matthewp

after reading your comment more carefully, i think we might agree on the following strategy (these changes would apply to the current state of this pr)

1. move `configureComponent` and `configureVirtual` into `core.js`
2. add `haunted` function to `core.js`, which composes `configureComponent`:
    ```js
    function haunted({render}) {
      return {
        component: configureComponent({render})
      }
    }
    ```

i think this might make everybody happy
- no breaking changes for existing haunted consumers
- new pattern is to `import {haunted} from "haunted/src/core.js"`
- consumers using `virtual` with lit-html can continue using the same pathway as before
- `configureVirtual` is available in `core.js` for any consumer looking to adapt a `lit-html` alternative themselves
- `configureComponent` is available in `core.js` anticipating a future where the `haunted` function might do more than just configuring a component

**Comment by WebReflection** [comment]
My only point is that an agnostic library shouldn't need in its core adapters for each library, rather provide a way to define adapters so that any library could use it.

Maybe the best way to do it is to split this library in a core able to provide such functionality, and keep haunted with lit-html default on top of such core?

In this way core shouldn't even include lit in its dependencies and any other lib could ship either an adapter or a hounted equivalent.

**Comment by matthewp** [comment]
@chase-moskal yes, we are close. The last thing I would say is that I don't think people should import stuff from `src/` at all. So make it `haunted/core.js` (which itself can import from src/) and we're good I think. So the two APIs would be 'haunted' for lit-html users and 'haunted/core' for people who want to adapt their own renderers.

**Comment by chase-moskal** [comment]
> My only point is that an agnostic library shouldn't need in its core adapters for each library, rather provide a way to define adapters so that any library could use it.

i guess we could just ditch `adaptLighterHtml` and ask consumers to do it themselves:

```js
import {render} from "lighterhtml"
import {haunted} from "haunted/core.js"

const component = haunted({
  render: (what, where) => render(where, () => what)
  // instead of:
  // render: adaptLighterHtml(render)
})
```

however, i think including the adapter can actually help communicate that `lighterhtml` is properly supported and not something the consumer has to hack in themselves

i want to note that if we made a separate `haunted-lighter`, the entirety of that package would be

```js
import {render, html} from "lighterhtml"
import {haunted} from "haunted/core.js"

const {component} = haunted({
  render: (what, where) => render(where, () => what)
})

export {component, html}
```

@matthewp 

>  I don't think people should import stuff from `src/` at all. So make it `haunted/core.js` (which itself can import from src/) and we're good I think. So the two APIs would be 'haunted' for lit-html users and 'haunted/core' for people who want to adapt their own renderers.

agreed, this sounds good :+1:

**Comment by matthewp** [comment]
I'd prefer `haunted-lighter` as a separate package for now, even though its small. Adding another dependency means that if that dependency has a major version bump we have to bump our major version as well.

I'd prefer to move away from having any library integrations in the future, once the template instantiation stuff is more fleshed out, and just follow that. If that happens presumably all libraries can "just work".

**Comment by WebReflection** [comment]
@matthewp are you saying `haunted-lighter` as a version without lit, or a version that includes lighterhtml?

**Comment by matthewp** [comment]
It would be this and include lighterhtml:

```js
import {render, html} from "lighterhtml"
import {haunted} from "haunted/core"

const {component} = haunted({
  render: (what, where) => render(where, () => what)
})

export * from "haunted/core"

export {component, html}
```

**Comment by matthewp** [comment]
👆 That would not include lit-html btw, because haunted/core will not include it.

**Comment by matthewp** [comment]
@chase-moskal are you planning on updating this?

**Comment by chase-moskal** [comment]
i'd love to if i have time, but that's unlikely for the next few weeks

the least i can do is re-read this thread and summarize in bullets the work that needs to be done from the current state of this PR

### work to be done from this point

1. move `configureComponent` and `configureVirtual` into `core.js`
2. add `haunted` function to `core.js`, which composes `configureComponent`:
    ```js
    function haunted({render}) {
      return {
        component: configureComponent({render})
      }
    }
    ```
3. the existing `component` module will import lit-html's `render` function and use it with `configureComponent` to export the preconfigured lit-html `component` that haunted users are already using (no breaking changes for users)

#### objectives and notes
- a new "haunted configuration function" pattern is introduced, allowing users to adapt haunted for new render libraries: `import {haunted} from "haunted/dist/core.js"`
- there should be no breaking changes for existing haunted consumers; the same `component` they can import is preconfigured for lit-html
- loading the `haunted` configuration itself function must *not* load lit-html at all (core.js does not import lit)
- consumers using `virtual` with lit-html can continue using the same pathway as before, it is not available via the new `haunted` configuration function
- `configureVirtual` is available in `core.js` for any consumer looking to adapt a `lit-html` alternative themselves
- `configureComponent` is available in `core.js` anticipating a future where the `haunted` function might do more than just configuring a component
- users should never import things from `haunted/src`, instead they should be using the dist path

**Comment by stevenvachon** [comment]
I think that lit-html should not be bundled with this library.

**Comment by matthewp** [comment]
@stevenvachon It might be difficult to follow from this discussion above, but the idea here is to have a `haunted/core` import that does not include lit-html that allows creating a configured version of haunted with whatever view library you want.

**Comment by stevenvachon** [comment]
@matthewp lit.js still exists in this PR, though

**Comment by matthewp** [comment]
It does indeed still exist, but it's not included in the `haunted/core` bundle so non lit-html users won't get the bundle size increase.  

How this PR is implemented isn't 100% how its going to wind up. @chase-moskal has done an amazing job laying the foundation here. I'm hoping to get around to this soon since it's a feature that a lot people want.

**Comment by chase-moskal** [comment]
@stevenvachon — i agree with you — ultimately, haunted's dependencies shouldn't be "hard-baked" into this repository — not even as an [unpkg link](https://github.com/matthewp/haunted/blob/master/src/lit.js#L1) as is currently the case

**changes planned in this pr will fix the problem via an alternative pathway**

- in this PR discussion, we've agreed to create a new alternative import pathway which avoids the bundle and lit-html
- this alternative pathway, `import {haunted} from "haunted/core.js"` should do enough to satisfy your concerns as well as mine :)

**however, the presence of `lit.js` is still in fact a problem for anyone using the original pathway**

- i've created a new issue ***#98 "How to import haunted — in the future!"*** to coalesce these thoughts and separate them from this pull request
- i'm beginning to think that before we continue implementation work on this agnostic branch, we should probably wait until changes from #98 are completed

@matthewp, @stevenvachon  
please see #98 and let me know what you think there

**Comment by matthewp** [comment]
Closing in favor of haunted/core which now covers this use case. https://github.com/matthewp/haunted/tree/a88c42958459428270c1993547e0a415cd76f152#importing

**Pull request closed without merging**
