### PR TITLE
Add missing component call in the observedAttributes example

### PR DESCRIPTION
**Pull request by juliettepretot**
This needs to be still wrapped by component. See https://github.com/matthewp/haunted/blob/fe66090bf0efa625ec4c52d25189ea1f18c3cc1c/test/test-attrs.js

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks!

**Comment by stevenvachon** [comment]
Why is `component()` used twice on the same object?

**Comment by matthewp** [comment]
@stevenvachon not sure I understand. If there's a bug in the docs you might want to open another issue.

**Comment by stevenvachon** [comment]
@matthewp the issue is directly related to this PR. If you look at the docs now, it's redundant:
```js
const App = component(({ name }) => {
  return html`Hello ${name}!`;
});

customElements.define('my-app', component(App));
```
(there're two uses of `component()` on the same object)

**Comment by matthewp** [comment]
Ah ok, thanks for catching this.

**Pull request merged**
