### PR TITLE
Add support for the delegatesFocus option when attaching the Shadow DOM

### PR DESCRIPTION
**Pull request by sunesimonsen**
Fixes: #89 

See https://developers.google.com/web/fundamentals/web-components/shadowdom#focus

### CODE REVIEW

**Comment by matthewp** [comment]
Thanks! Instead of adding this flag to the options object, I'm thinking we should allowing passing in the [shadowRootInit](https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow#Parameters) object. This way if future options are added we don't need to add each one to Haunted.

So it would be:

```js
customElements.define('delegates-focus', component(() => {
    return html`delegates focus`;
}, HTMLElement, { shadowRootInit: { mode: 'open', delegatesFocus: true } }));
```

How does that sound? Also allows someone to set it to `mode: 'closed'` if they wanted.

**Comment by sunesimonsen** [comment]
I think that sounds like a better idea, I'll update the PR.

**Comment by sunesimonsen** [comment]
I updated the PR with the changes you asked for.

I couldn't figure out if I needed to add some documentation to the readme.

**Comment by matthewp** [comment]
Looks really good, thank you!

**Comment by matthewp** [comment]
Released as 4.4.0. Thanks so much! https://github.com/matthewp/haunted/releases/tag/v4.4.0

**Pull request merged**
