### PR TITLE
chore(test-context): Tests for slotted context

### PR DESCRIPTION
**Pull request by noahlaux**
After working a bit with your awesome take on hooks in webcomponents, I stumbled upon an issue having context hooks in slots. IMHO they should just work no matter where you put them in the DOM/shadowDOM. I see that you emit events with the `composed: true` flag, so not sure why it shouldn't work. 

From a tiny little debugging, it seems like a race condition where the slotted content is not registered to the event listeners pool. Interestingly thought it seems like the `<generic-consumer .render` pattern has the right value.

I can try to debug more, but maybe you know exactly what's up here, if not, I'm
willing to give it a go. I made a test for what I'm experiencing, I hope it makes sense to you.

### CODE REVIEW

**Comment by matthewp** [comment]
Hey thanks so much for adding a test for a bug @noahlaux, that's amazing!  I won't be able to take a look in the next couple of days but will when i have the time. Thanks again!

**Comment by matthewp** [comment]
Hey, @noahlaux I took a look and my suspicion is that this is a side-effect of Haunted's asynchronous scheduler. The 'slotted-context-provider' element hasn't rendered by the time the event is called. Still digging into it.

**Comment by matthewp** [comment]
One solution that seems to work is if context subscriptions occur in `useEffect` timing. Playing around with that idea. Wondering if in React if you get a context the first time `useContext()` is called or not.

**Comment by matthewp** [comment]
Is it acceptable if you get the "wrong" context the first time it runs, but then it reruns after a useEffect and from that point forward you are subscribed to the correct context?

**Comment by matthewp** [comment]
I have a fix that works like this:

1. `useContext()` is called and gets the nearest context within the light DOM.
2. The parent component renders.
3. Effects are called of which the useContext code has registered.
4. useContext unsubscribes from the light DOM context and subscribes to the one within the shadowRoot.
5. The renderer reruns and gets the right context value.

**Comment by matthewp** [comment]
Another possible solution is deeply render elements; don't want for connectedCallback for rendering. That one scares me just slightly but its worth a try.

**Comment by matthewp** [comment]
I'm going to go with the useEffect style fix. It's possible that changing the way the scheduler works in the future would also fix this, but that's for down the line.

**Comment by matthewp** [comment]
Need to close this in order to open a new PR with the same branch name.

**Comment by matthewp** [comment]
New PR: https://github.com/matthewp/haunted/pull/104

**Comment by christophediprima** [comment]
Hi @matthewp ! I am trying to make a port of @apollo/react-hooks with haunted.
The useQuery hook they have really needs to have the context at first render.
Do you have any plans to support this with slot?

**Comment by matthewp** [comment]
I'm not sure I understand, I would gladly take a contribution though. Please file an issue and we can discuss more.

**Comment by christophediprima** [comment]
#172

**Pull request closed without merging**
